<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('service_codes', function (Blueprint $table) {
            $table->bigIncrements('service_code_id');
            $table->string('code');
            $table->string('description');
            $table->boolean('is_hospital')->default(false);
            $table->string('age')->nullable();
            $table->string('gender')->nullable();
            $table->double('prescribed_amount')->default(0);
            $table->string('status');
            $table->timestamps();
        });

        \App\Models\Api\V1\ServiceProviders\ServiceCode::insert([
            ['code' => '0', 'description' => 'See Notes', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0001', 'description' => 'Exclusion', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0002', 'description' => 'Administration Fee', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0003', 'description' => 'EXPIRED - Limit Report', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0004', 'description' => 'Force Code For Available Day-to-day', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0005', 'description' => 'Debt', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0006', 'description' => 'Credit Received', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0007', 'description' => 'Debt Deduction', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0008', 'description' => 'Debt Payment', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0009', 'description' => 'Credit Re-imbursement', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0101', 'description' => 'Consultation', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0101', 'description' => 'AIMS Admin Fee', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0103', 'description' => 'Covid Consultation & Treatment', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2200, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0109', 'description' => 'Visit - In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0111', 'description' => 'Anaesthetic / Sedation', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '0201', 'description' => 'Material', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '07', 'description' => 'Acute Medication - With Co-payment', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '103', 'description' => 'Covid Consultation & Treatment', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2200, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '107', 'description' => 'Acute Medication - Without Co-payment', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '11501', 'description' => 'Optometry - All Inclusive', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 8000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '11502', 'description' => 'Optometry - Eye Test', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 1000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '11503', 'description' => 'Optometry - Frames', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 8000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '11504', 'description' => 'Optometry - Lenses', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 8000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '11505', 'description' => 'Optometry - Contact Lenses', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 5000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13200', 'description' => 'Medical Emergency Services - By Road', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13201', 'description' => 'Medical Emergency services  - By Air', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13202', 'description' => 'Travel Companion\'s Flight', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13203', 'description' => 'Return Flight', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13204', 'description' => 'Repatriation', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13205', 'description' => 'Transport With Cheetah Express', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13206', 'description' => 'Non-emergency Evacuation', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 30000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '13207', 'description' => 'EXPIRED - Funeral Cover', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '14101', 'description' => 'Funeral Cover', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '1461', 'description' => 'Dental Sedation', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 1000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '1601', 'description' => 'Prenatal Consultation', 'gender' => 'Female', 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '1610', 'description' => 'Dr\'s Fees - Premature', 'gender' => 'Female', 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '1615', 'description' => 'Maternity Registration', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '1652', 'description' => 'Prenatal Pathology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '207', 'description' => 'Vaccination', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 6000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2100', 'description' => 'Procedures And Surgery', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2101', 'description' => 'Diagnostic Procedures', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2102', 'description' => 'Procedures And Treatment', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 500, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2103', 'description' => 'Diagnostic Procedures - In Hospital Scopes', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2104', 'description' => 'Covid Vaccine Administration', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2105', 'description' => 'Ex-gratia', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2106', 'description' => 'Estoppel', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2107', 'description' => 'Diagnostic Procedures', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 3000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2137', 'description' => 'Dr\'s Fees - Circumcision', 'gender' => 'Male', 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 10000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2201', 'description' => 'Psychiatric Session', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2283', 'description' => 'Expired - Hymanectomy (doctor´s Invoice)', 'gender' => 'Female', 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2300', 'description' => 'Expired - Oncology - Surgery', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2500', 'description' => 'Professional Fees - Organ Transplant', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2601', 'description' => 'Consultation Ophthalmologist', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2614', 'description' => 'Maternity Fees (doctor´s Invoice)', 'gender' => 'Female', 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2615', 'description' => 'Expired - Normal Delivery', 'gender' => 'Female', 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2801', 'description' => 'Dr\'s Fees - Spinal Column Surgery', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '2802', 'description' => 'Dr\'s Fees - Joint Replacement Surgery', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '307', 'description' => 'Vitamins & Supplements	Vitaminas', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 600, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '3594', 'description' => 'Mammogram', 'gender' => 'Female', 'age' => 40, 'is_hospital' => false, 'prescribed_amount' => 4200, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '3615', 'description' => 'Prenatal Scan', 'gender' => 'Female', 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '3801', 'description' => 'General Radiology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '3802', 'description' => 'Specialised Radiology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '3979', 'description' => 'Covid Pathology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 4250, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '407', 'description' => 'Covid Medicine', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '4566', 'description' => 'Pap Smear', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '4601', 'description' => 'Prostate Test (PSA)', 'gender' => 'Male', 'age' => 40, 'is_hospital' => false, 'prescribed_amount' => 2200, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '47001', 'description' => 'Rehabilitation (All Inclusive)', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '5007', 'description' => 'Professional Fees - Dialysis', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '507', 'description' => 'Covid Vaccine', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '5201', 'description' => 'General Pathology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 3000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '5238', 'description' => 'General Radiology & Pathology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58000', 'description' => 'Hospital Fees - Unspecified 100%', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58001', 'description' => 'Hospital Fees - 100%', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58002', 'description' => 'Parental Accomodation', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58003', 'description' => 'Hospital Fees - Complications In Pregnancy', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58004', 'description' => 'Travel Companion\'s Accomodation', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58005', 'description' => 'Covid: Normal Care In Isolation', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58007', 'description' => 'TTO (Medication provide in hospital To Take Home)', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58009', 'description' => 'Hospital Fees - No Pre-authorization 20 % Penalty', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58015', 'description' => 'EXPIRED - Hospital Fees - Radio & Chemo Therapy', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58019', 'description' => 'Hospital Fees - Neonatal Icu/high Care', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58020', 'description' => 'Hospital Fees - Organ Transplant', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58021', 'description' => 'Hospital Fees - Oncology', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58030', 'description' => 'Emergency Room - Red', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58031', 'description' => 'Emergency Room - Green', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 5000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58038', 'description' => 'Radiology - In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58050', 'description' => 'Hospital Fees - 50%', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58052', 'description' => 'Pathology - In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58066', 'description' => 'Occupational Therapy - In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58072', 'description' => 'Physiotherapy - In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58075', 'description' => 'Clinical Technology In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58082', 'description' => 'Speech Therapy & Audiology - In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58084', 'description' => 'Nutritional Services - In Hospital', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58100', 'description' => 'Hospital Fees - Icu, High Care And Isolation', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58101', 'description' => 'Covid Icu Care In Isolation', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58137', 'description' => 'Hospital Fees - Circumcision', 'gender' => 'Male', 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58150', 'description' => 'Hospital Fees - Icu, High Care And Isolation 50%', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58181', 'description' => 'Hospital Fees - Dental Procedures', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58199', 'description' => 'Hospital Fees - Maximum Days Exceeded', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58201', 'description' => 'Hospital Fees - Material', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58221', 'description' => 'Hosptial Fees - Mental Health', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58283', 'description' => 'Expired - Hospital Fees - Hymanectomy', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58614', 'description' => 'Hospital Fees - Maternity', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58615', 'description' => 'Expired - Hospital Fees', 'gender' => 'Female', 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58801', 'description' => 'Hospital Fees - Spinal Column Surgery', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58802', 'description' => 'Hospital Fees - Joint Replacement Surgery', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58849', 'description' => 'Hospital Fees - Dialysis', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '58999', 'description' => 'Expired - Hospital Fees - General 0%', 'gender' => null, 'age' => null, 'is_hospital' => true, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '6007', 'description' => 'Anti-retroviral Therapy - Wellness Program', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2500, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '6052', 'description' => 'Pathology - Wellness Program', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2500, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '6101', 'description' => 'Consultation - Wellness Program', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2500, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '6238', 'description' => 'Hiv Pathology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 6000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '66000', 'description' => 'Occupational Therapy', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '7201', 'description' => 'Physiotherapy', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '7510', 'description' => 'Clinical Technology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '7810', 'description' => 'Blood Transfusion', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '8007', 'description' => 'Oncology Treatment (all Inclusive)', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '8180', 'description' => 'Basic Dentistry', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 5000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '8183', 'description' => 'Dentures (plastic / Metal)', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 15000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '8184', 'description' => 'Crowns', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 15000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '8185', 'description' => 'Orthodontics', 'gender' => null, 'age' => 18, 'is_hospital' => false, 'prescribed_amount' => 15000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '82000', 'description' => 'Speech Therapy & Audiology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 5000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '8238', 'description' => 'Expired - Diagnostic Procedures - Oncology', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '84000', 'description' => 'Nutritional Services', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '88000', 'description' => 'Stepdown And Rehabilitation 100%', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '88001', 'description' => 'Private Nursing', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '88100', 'description' => 'Stepdown and Rehabilitation 100%', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '9007', 'description' => 'Chronic Medication', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 2500, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99000', 'description' => 'Medical Appliances', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 5000, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99002', 'description' => 'Prosthesis - Evars', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99003', 'description' => 'Prosthesis - Vascular', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99004', 'description' => 'Prosthesis - Functional', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99005', 'description' => 'Prosthesis - Reconstructive', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99006', 'description' => 'EXPIRED - Implants', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'inactive', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99007', 'description' => 'EXPIRED - Intra-Occular Lens', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99008', 'description' => 'Cochlear Device', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99201', 'description' => 'Oxygen', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => '99999', 'description' => 'Imports', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['code' => 'W1', 'description' => 'Waiting Period', 'gender' => null, 'age' => null, 'is_hospital' => false, 'prescribed_amount' => 0, 'status' => 'active', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('service_codes');
    }
};
